# Changes here will be overwritten by Copier
_commit: v0.0.12
_src_path: https://github.com/AmpelAstro/copier-ampel
author_email: jakob.van.santen@desy.de
author_name: Jakob van Santen
plugin_description: LSST alert archive for the Ampel system
plugin_name: LSST-archive
plugin_org: AmpelAstro
plugin_version: 0.0.1-alpha.0
version_cap: <0.11
