# Changes here will be overwritten by Copier
_commit: v0.0.15
_src_path: https://github.com/AmpelAstro/copier-ampel
plugin_description: LSST alert archive for the Ampel system
plugin_name: LSST-archive
plugin_org: AmpelAstro
plugin_version: 0.0.1-alpha.0
user_email: jakob.van.santen@desy.de
user_name: Jakob van Santen
version_cap: <0.11
