"""object table

Revision ID: 05b7ccfc1440
Revises: 0dd96901dfe1
Create Date: 2025-10-23 16:07:22.225837

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05b7ccfc1440"
down_revision: str | Sequence[str] | None = "0dd96901dfe1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diaobject",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("validityStartMjdTai", sa.Float(), nullable=True),
        sa.Column("firstDiaSourceMjdTai", sa.Float(), nullable=True),
        sa.Column("lastDiaSourceMjdTai", sa.Float(), nullable=True),
        sa.Column("nDiaSources", sa.Integer(), nullable=True),
        sa.Column("ra", sa.Float(), nullable=True),
        sa.Column("dec", sa.Float(), nullable=True),
        sa.Column("hpx", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ssobject",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("designation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("alert", sa.Column("diaobject_id", sa.BigInteger(), nullable=True))
    op.add_column("alert", sa.Column("ssobject_id", sa.BigInteger(), nullable=True))

    op.execute("""
        UPDATE alert SET diaobject_id = object_id WHERE object_id != 0;
               """)
    op.execute("""
        INSERT INTO diaobject (id) (SELECT DISTINCT object_id FROM alert WHERE object_id != 0)
    """)
    op.drop_column("alert", "object_id")

    op.create_foreign_key(
        "alert_ssobject_id_fkey", "alert", "ssobject", ["ssobject_id"], ["id"]
    )
    op.create_foreign_key(
        "alert_diaobject_id_fkey", "alert", "diaobject", ["diaobject_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "alert",
    #     sa.Column("object_id", sa.BIGINT(), autoincrement=False, nullable=False),
    # )
    op.add_column(
        "alert",
        sa.Column("object_id", sa.BigInteger(), nullable=False, server_default="0"),
    )
    op.execute("""
        UPDATE alert SET object_id = diaobject_id WHERE diaobject_id IS NOT NULL;
    """)
    op.drop_constraint("alert_ssobject_id_fkey", "alert", type_="foreignkey")
    op.drop_constraint("alert_diaobject_id_fkey", "alert", type_="foreignkey")
    op.drop_column("alert", "ssobject_id")
    op.drop_column("alert", "diaobject_id")
    op.drop_table("ssobject")
    op.drop_table("diaobject")
    # ### end Alembic commands ###
