name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:0.12.19.1 
        env:
          SERVICES: s3
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install -E server
    - run: poetry run pytest --cov=ampel --integration
      env:
        LOCALSTACK_PORT: 4566
  
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install -E server
    - run: poetry run mypy --namespace-packages -p ampel
