name: ci

on:
  push:
    branches:
      - main
      - renovate/*
      - dev/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - dev/*
      - stable/*

jobs:
  ci:
    uses: AmpelProject/Ampel-interface/.github/workflows/ci.yml@6744df5a70735c261659a10d8819f11f5780ecbd
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    with:
      mongo: false
      localstack: true
      lint: false
      format: false
      # renovate: datasource=conda depName=conda-forge/python
      python-version: "3.9"
      # renovate: datasource=pypi depName=ruff
      ruff-version: "0.4.5"
